# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('intrinsic', models.TextField(blank=True, null=True)),
                ('distortion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('cameraID', models.IntegerField(default=0)),
                ('cameraType', models.CharField(max_length=200)),
                ('resolution', models.CharField(max_length=20)),
                ('calibrated', models.BooleanField(default=False)),
                ('focusX', models.FloatField(default=0)),
                ('focusY', models.FloatField(default=0)),
                ('uCount', models.FloatField(default=0)),
                ('vCount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Campose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('coordx', models.FloatField(default=0)),
                ('coordy', models.FloatField(default=0)),
                ('coordz', models.FloatField(default=0)),
                ('anglex', models.FloatField(default=0)),
                ('angley', models.FloatField(default=0)),
                ('anglez', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResolutionX', models.IntegerField(default=0)),
                ('ResolutionY', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('folderName', models.CharField(max_length=200)),
                ('imageCount', models.IntegerField(default=0)),
                ('ResolutionX', models.IntegerField(default=0)),
                ('ResolutionY', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibrate.ImageFolder'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calibrate.Camera'),
        ),
    ]
